#define FUNC       1
#define VAR        2
#define READ       3
#define PRINT      4
#define ID         5
#define INTLITERAL 6
#define LPAREN     7
#define RPAREN     8
#define SEMICOLON  9
#define COMMA      10
#define ASSIGNOP   11
#define PLUSOP     12
#define MINUSOP    13
#define REALLIT    14
#define LCORCH     15
#define RCORCH     16
#define EQUAL      17
#define LET        18
#define IF         19
#define ELSE       20
#define WHILE      21
#define INT        22
#define FLOAT      23
#define BOOL       24
#define FLOATLITERAL 25
#define MAEQU      26
#define MIEQU      27
#define SUP        28
#define INF        29
#define NOTEQU     30
#define AND        31
#define OR         32
#define NOT        33
#define OROP       34
#define ANDOP      35
#define CADENA     36
#define BOOLLIT    37
#define MULT       38
#define MOD        39
#define DIVI       40
